In [1]:
import numpy as np

In [3]:
# question no 3
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [5]:
result = np.vstack((a,b))
print(result)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# question number 4
arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
rev = arr1[::-1]
print(rev)

[10  9  8  7  6  5  4  3  2  1]


In [10]:
# question number 5
arr2 = np.arange(0, 9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
# question number 6
arr3 = np.array([1,2,0,0,4,0])
np.nonzero(arr3)

(array([0, 1, 4]),)

In [4]:
# question number 7
arr4 = np.random.random((10,10))

In [5]:
arr4

array([[0.59707181, 0.47553217, 0.36697706, 0.11169177, 0.43831035,
        0.86259573, 0.10473435, 0.40749175, 0.81781926, 0.84429109],
       [0.91091446, 0.96278365, 0.89867266, 0.40192902, 0.50879731,
        0.15682937, 0.15242928, 0.18628068, 0.83948347, 0.14664858],
       [0.51495876, 0.50660119, 0.85305864, 0.54936527, 0.38138963,
        0.24740265, 0.44495453, 0.0600277 , 0.32684481, 0.98946754],
       [0.24961187, 0.49702572, 0.08453791, 0.2729566 , 0.97011415,
        0.81333656, 0.44348088, 0.52259186, 0.47888516, 0.40821581],
       [0.056681  , 0.70658532, 0.40460706, 0.92483058, 0.31676632,
        0.32532148, 0.79720443, 0.62901715, 0.45490009, 0.98184869],
       [0.37705214, 0.30173822, 0.55991739, 0.14673385, 0.34575759,
        0.04749801, 0.72555755, 0.33644149, 0.90174136, 0.73298206],
       [0.88928128, 0.52977227, 0.09028564, 0.08039449, 0.37430951,
        0.2359574 , 0.64357348, 0.16855236, 0.62159399, 0.43765942],
       [0.57719212, 0.04689095, 0.9260462

In [6]:
 min_value = arr4.min()
 max_value = arr4.max()

In [7]:
print(min_value,max_value)

0.007056663855626866 0.9894675421204252


In [8]:
# question number 8
arr5 = np.arange(1,31)

In [9]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [10]:
arr5.mean()

15.5

In [11]:
# question number 9

oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
# question number 10
zero_border = np.zeros((10,10))
zero_border[1:-1, 1:-1] = 1
print(zero_border)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
# question number 11
arr6 = np.diag(1+np.arange(4), k = -1)
print (arr6)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [2]:
# question number 12

arr_7= np.random.random((5,5))
print(arr_7)
arr_max, arr_min = arr_7.max(), arr_7.min()
normalized = (arr_7 - arr_min)/(arr_max - arr_min)
print("After normalization:")
print(normalized)

[[0.68828292 0.62155027 0.93891044 0.54521117 0.01745667]
 [0.82206192 0.69363873 0.44034198 0.33315948 0.89825425]
 [0.36226193 0.51613146 0.08694463 0.22545938 0.44608514]
 [0.90047795 0.45155612 0.76747966 0.14068233 0.16310387]
 [0.23332345 0.74067831 0.62944084 0.0753016  0.96457482]]
After normalization:
[[0.70828148 0.63782286 0.97290265 0.5572214  0.        ]
 [0.84952997 0.71393633 0.44649689 0.33332991 0.92997645]
 [0.36405729 0.52651804 0.07336779 0.21961643 0.45256072]
 [0.93232431 0.45833717 0.79190013 0.1301059  0.15377934]
 [0.22791959 0.76360234 0.64615398 0.06107467 1.        ]]


In [3]:
# question number 13
array9 = np.array([0, 10, 20, 40, 60])
array10 = [10, 30, 40]

print("Common values ")
print(np.intersect1d(array9, array10))

Common values 
[10 40]


In [4]:
# question number 14
def generate(): 
    for x in range(10):
        yield x
res_ = np.fromiter(generate(), dtype=float, count=-1)
print (res_)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [7]:
# question number 15

arr11 = np.random.rand(3, 5)

mean_row = arr11 - arr11.mean(axis=1, keepdims=True)
mean_row

array([[-0.16167764, -0.26757062,  0.13628457,  0.28636495,  0.00659873],
       [-0.06887934,  0.13970871, -0.15673647,  0.02151102,  0.06439608],
       [ 0.44458594, -0.33519241, -0.53595434, -0.03033337,  0.45689418]])